#!/usr/bin/python
# -*- coding: utf-8 -*-

import textwrap
from . import constants, geometry, helper
from .config import Config


class Translator:

    def __init__(self, language=Config().default_language):
        if language in constants.supported_language_list:
            self.language = language
        else:
            self.language = Config().default_language


    def translate(self, category, tag):
        if self.language == "de":
            translation = self.translate_to_german(category, tag)
        else:
            translation = self.translate_to_english(category, tag)
        return translation


    def translate_to_german(self, category, tag):
        if category == "message":
            if tag == "map_not_available_or_incompatible": return "Karte ist nicht verfügbar oder inkompatibel"
            if tag == "database_error": return "Fehler bei der Datenbankabfrage"
            if tag == "no_route_options": return "Keine Routenoptionen übermittelt"
            if tag == "no_route_factor_option": return "Der Faktor für die Berechnung des Umweges fehlt"
            if tag == "no_session_id_option": return "Die Session Id fehlt"
            if tag == "old_request_still_running": return "Eine Anfrage von Ihnen wird bereits bearbeitet. Sie können in 3 Minuten fortfahren."
            if tag == "server_busy": return "Der Server ist gerade ausgelastet, Bitte versuchen Sie es später erneut."
            if tag == "no_source_route": return "Keine Route übermittelt"
            if tag == "source_route_incomplete": return "Die übermittelte Routinganfrage ist unvollständig"
            if tag == "no_start_point": return "Kein Startpunkt übermittelt"
            if tag == "start_point_no_name": return "Dem übermittelten Startpunkt fehlt der Name"
            if tag == "start_point_no_latitude": return "Dem übermittelten Startpunkt fehlt der Breitengrad"
            if tag == "start_point_no_longitude": return "Dem übermittelten Startpunkt fehlt der Längengrad"
            if tag == "start_point_no_type": return "Dem übermittelten Startpunkt fehlt der Typ"
            if tag == "no_way_id": return "Keine Weg-Id übermittelt"
            if tag == "no_node_id": return "Keine Node-Id übermittelt"
            if tag == "no_next_node_id": return "Keine Next-Node-Id übermittelt"
            if tag == "node_id_invalid": return "Die übermittelte Wegpunkt-Id ist ungültig"
            if tag == "way_id_invalid": return "Die übermittelte Weg-Id ist ungültig"
            if tag == "source_route_no_transport_parts": return "Der Route fehlt ein, per ÖPNV zurückzulegender Routenabschnitt"
            if tag == "source_route_multiple_transport_parts": return "Die Route beinhaltet mehr als einen, per ÖPNV zurückzulegenden Routenabschnitt"
            if tag == "no_address_string": return "Keine Adresse übermittelt"
            if tag == "address_invalid": return "Für die gegebenen Adresse sind keine Koordinaten ermittelbar"
            if tag == "no_latitude_value": return "Kein Breitengrad übermittelt"
            if tag == "no_longitude_value": return "Kein Längengrad übermittelt"
            if tag == "no_range_value": return "Kein Wert für den Umkreis übermittelt"
            if tag == "no_tags_value": return "Keine POI Tags übermittelt"
            if tag == "no_public_transport_provider": return "Kein ÖPNV Anbieter übermittelt"
            if tag == "no_address_for_this_coordinates": return "Für die übergebenen Koordinaten konnte keine Adresse ermittelt werden"
            if tag == "no_station_for_this_coordinates": return "Die Haltestelle konnte nicht ermittelt werden"
            if tag == "bahn_server_down": return "Der Server der Deutschen Bahn ist nicht erreichbar"
            if tag == "no_bug_report_file_name": return "Kein Dateiname für den Fehlerbericht übertragen"
            if tag == "no_bug_report_contents": return "Der Fehlerbericht ist leer"
            if tag == "process_canceled": return "Prozess abgebrochen"

        if category == "footway_creator":
            if tag == "first_segment": return "Namenloses Wegsegment"
            if tag == "last_segment": return "Namenloses Wegsegment"
            if tag == "via_point_label": return "Zwischenziel %d: %s"
            if tag == "route_description_without_transport": return textwrap.dedent("""\
                    Die Route ist %d Meter lang und besteht aus %d Kreuzungen.""")
            if tag == "route_description_with_single_transport": return textwrap.dedent("""\
                    Die Route ist %d Meter lang. Sie besteht aus %d Kreuzungen und einer Fahrt mit dem ÖPNV. 
                    Abfahrt in %d Minuten von der Station %s mit der Linie %s nach %s.""")
            if tag == "route_description_with_multi_transport": return textwrap.dedent("""\
                    Die Route ist %d Meter lang. Sie besteht aus %d Kreuzungen und %d Fahrten mit dem ÖPNV. 
                    Erste Abfahrt in %d Minuten von der Station %s mit der Linie %s nach %s.""")

        if category == "transport_creator":
            if tag == "footway_place_holder": return "Platzhalter für eine zu Fuß zurückzulegende Strecke"
            if tag == "same_station": return "Weiterfahrt von gleicher Haltestelle"
            if tag == "opposite_station": return "Weiterfahrt von gegenüberliegender Haltestelle"
            if tag == "nearby_station": return "Weiterfahrt von benachbarter Haltestelle"
            if tag == "nearby_station_no_exact_pos": return "Weiterfahrt von benachbarter Haltestelle, genaue Haltestellenposition nicht bekannt"
            if tag == "within_station": return "Weiterfahrt innerhalb dieser Station"
            if tag == "different_station": return "Weiterfahrt von anderer Station"
            if tag == "transport_route_description": return textwrap.dedent("""\
                    Abfahrt in %d Minuten, Fahrzeit: %d Minuten, %d mal umsteigen, 
                    Verkehrsmittel: %s, Fußweg: %d Meter""")
            if tag == "transport_route_description_no_time": return textwrap.dedent("""\
                    Abfahrt in %d Minuten, Fahrzeit: %d Minuten, %d mal umsteigen (wenig Zeit), 
                    Verkehrsmittel: %s, Fußweg: %d Meter""")

        if category == "poi":
            if tag == "address": return "Adresse"
            if tag == "hiking_trail": return "Wanderweg"
            if tag == "way_point": return "Wegpunkt"
            if tag == "way_segment": return "Wegsegment"

        if category == "smoothness":
            if tag == "excellent": return "Sehr gut"
            if tag == "good": return "Gut"
            if tag == "intermediate": return "Mittelmäßig"
            if tag == "bad": return "Schlecht"
            if tag == "very_bad": return "Schlecht"
            if tag == "horrible": return "Sehr schlecht"
            if tag == "very_horrible": return "Sehr schlecht"
            if tag == "impassable": return "Für Fahrzeuge unpassierbar"

        if category == "surface":
            if tag == "unpaved": return "Unbefestigt"
            if tag == "paved": return "befestigt"
            if tag == "asphalt": return "Asphalt"
            if tag == "cobblestone:flattened": return "Kopfsteinpflaster"
            if tag == "cobblestone": return "Kopfsteinpflaster"
            if tag == "concrete:plates": return "Betonspurplatten"
            if tag == "concrete:lanes": return "Betonspurplatten"
            if tag == "concrete": return "Beton"
            if tag == "paving_stones:20": return "Pflastersteine"
            if tag == "paving_stones:30": return "Pflastersteine"
            if tag == "paving_stones": return "Pflastersteine"
            if tag == "sett": return "Pflastersteine"
            if tag == "compacted": return "Befestigter Kies"
            if tag == "fine_gravel": return "Befestigter Kies"
            if tag == "earth": return "Trampelpfad"
            if tag == "ground": return "Trampelpfad"
            if tag == "grass_paver": return "Rasengittersteine"
            if tag == "grass": return "Gras"
            if tag == "metal": return "Metall"
            if tag == "gravel": return "Grober Schotter"
            if tag == "pebblestone": return "Kies"
            if tag == "sand": return "Sand"
            if tag == "mud": return "Matsch"
            if tag == "ice": return "Eis"
            if tag == "snow": return "Schnee"
            if tag == "wood": return "Holz"
            if tag == "tartan": return "Tartanbelag"
            if tag == "artificial_turf": return "Kunstrasen"
            if tag == "decoturf": return "Kunstrasen"
            if tag == "clay": return "Ascheplatz"

        if category == "aeroway":
            if tag == "aerodrome": return "Flughafen"
            if tag == "terminal": return "Flughafenterminal"

        if category == "amenity":
            if tag == "animal_boarding": return "Tierheim"
            if tag == "animal_shelter": return "Tierheim"
            if tag == "arts_centre": return "Kulturzentrum"
            if tag == "atm": return "Geldautomat"
            if tag == "auditorium": return "Hörsaal"
            if tag == "bank": return "Bank"
            if tag == "bar": return "Bar"
            if tag == "bbq": return "Grillplatz"
            if tag == "bench": return "Bank"
            if tag == "bicycle_parking": return "Fahrradstellplatz"
            if tag == "bicycle_rental": return "Fahrradverleih"
            if tag == "brothel": return "Bordell"
            if tag == "bureau_de_change": return "Wechselstube"
            if tag == "bus_station": return "Busbahnhof"
            if tag == "cafe": return "Café"
            if tag == "car_rental": return "Autovermietung"
            if tag == "car_sharing": return "Carsharing"
            if tag == "car_wash": return "Autowaschanlage"
            if tag == "casino": return "Casino"
            if tag == "cinema": return "Kino"
            if tag == "clinic": return "Krankenhaus"
            if tag == "club": return "Verein"
            if tag == "college": return "Hochschule"
            if tag == "community_centre": return "Gemeinschaftszentrum"
            if tag == "courthouse": return "Gericht"
            if tag == "crematorium": return "Krematorium"
            if tag == "dentist": return "Zahnarzt"
            if tag == "doctors": return "Arzt"
            if tag == "dormitory": return "Studentenwohnheim"
            if tag == "drinking_water": return "Trinkwasser"
            if tag == "driving_school": return "Fahrschule"
            if tag == "embassy": return "Botschaft"
            if tag == "emergency_phone": return "Notrufsäule"
            if tag == "fast_food": return "Schnellimbiss"
            if tag == "ferry_terminal": return "Fähranlegestelle"
            if tag == "fire_hydrant": return "Hydrant"
            if tag == "fire_station": return "Feuerwehr"
            if tag == "fountain": return "Springbrunnen"
            if tag == "fuel": return "Tankstelle"
            if tag == "grave_yard": return "Friedhof"
            if tag == "gym": return "Turnhalle"
            if tag == "hall": return "Halle"
            if tag == "health_centre": return "Gesundheitszentrum"
            if tag == "hospital": return "Krankenhaus"
            if tag == "hotel": return "Hotel"
            if tag == "hunting_stand": return "Hochstand"
            if tag == "ice_cream": return "Eisdiele"
            if tag == "kindergarten": return "Kindergarten"
            if tag == "kneipp_water_cure": return "Kneipp"
            if tag == "library": return "Bücherei"
            if tag == "market": return "Markt"
            if tag == "marketplace": return "Marktplatz"
            if tag == "mountain_rescue": return "Bergrettung"
            if tag == "nightclub": return "Nachtklub"
            if tag == "nursery": return "Kinderkrippe"
            if tag == "nursing_home": return "Pflegeheim"
            if tag == "office": return "Büro"
            if tag == "park": return "Park"
            if tag == "parking": return "Parkplatz"
            if tag == "pharmacy": return "Apotheke"
            if tag == "place_of_worship": return "Andachtsstätte"
            if tag == "police": return "Polizei"
            if tag == "post_box": return "Briefkasten"
            if tag == "post_office": return "Postamt"
            if tag == "preschool": return "Vorschule"
            if tag == "prison": return "Gefängnis"
            if tag == "pub": return "Kneipe"
            if tag == "public_building": return "öffentliches Gebäude"
            if tag == "public_market": return "öffentlicher Markt"
            if tag == "reception_area": return "Empfangsbereich"
            if tag == "recycling": return "Recyclingeinrichtung"
            if tag == "restaurant": return "Restaurant"
            if tag == "retirement_home": return "Altersheim"
            if tag == "sauna": return "Sauna"
            if tag == "school": return "Schule"
            if tag == "shelter": return "Schutzhütte"
            if tag == "shop": return "Geschäft"
            if tag == "shopping": return "Einkaufszentrum"
            if tag == "social_club": return "Geselligkeitsverein"
            if tag == "studio": return "Studio"
            if tag == "supermarket": return "Supermarkt"
            if tag == "swingerclub": return "Swingerclub"
            if tag == "taxi": return "Taxistand"
            if tag == "telephone": return "Telefonzelle"
            if tag == "theatre": return "Theater"
            if tag == "toilets": return "WC"
            if tag == "townhall": return "Rathaus"
            if tag == "university": return "Universität"
            if tag == "vending_machine": return "Automat"
            if tag == "veterinary": return "Tierarzt"
            if tag == "village_hall": return "Gemeindezentrum"
            if tag == "waste_basket": return "Mülleimer"
            if tag == "wifi": return "WLAN-Access-Point"
            if tag == "youth_centre": return "Jugendzentrum"

        if category == "building":
            if tag == "apartments": return "Wohnblock"
            if tag == "block": return "Gebäudeblock"
            if tag == "bunker": return "Bunker"
            if tag == "chapel": return "Kapelle"
            if tag == "church": return "Kirche"
            if tag == "city_hall": return "Rathaus"
            if tag == "commercial": return "Gewerbegebäude"
            if tag == "dormitory": return "Studentenwohnheim"
            if tag == "entrance": return "Eingang"
            if tag == "faculty": return "Ausbildungsgebäude"
            if tag == "farm": return "Bauernhof"
            if tag == "flats": return "Wohnung"
            if tag == "garage": return "Garage"
            if tag == "hall": return "Halle"
            if tag == "hospital": return "Spital"
            if tag == "hotel": return "Hotel"
            if tag == "house": return "Haus"
            if tag == "industrial": return "Industriegebäude"
            if tag == "office": return "Bürogebäude"
            if tag == "public": return "öffentliches Gebäude"
            if tag == "residential": return "Wohngebäude"
            if tag == "retail": return "Einzelhandelsgebäude"
            if tag == "school": return "Schulgebäude"
            if tag == "shop": return "Geschäft"
            if tag == "stadium": return "Stadion"
            if tag == "store": return "Warenhäuser"
            if tag == "terrace": return "Terrasse"
            if tag == "tower": return "Turm"
            if tag == "train_station": return "Bahnhof"
            if tag == "university": return "Universitätsgebäude"
            if tag == "building": return "Gebäude"

        if category == "entrance":
            if tag == "yes": return "Eingang"
            if tag == "main": return "Haupteingang"
            if tag == "service": return "Hintereingang"
            if tag == "emergency": return "Notausgang"
            if tag == "exit": return "Nur Ausgang"
            if tag == "subway_entrance": return "U-Bahn-Zugang"
            if tag == "entrance": return "Eingang"

        if category == "highway":
            if tag == "bridleway": return "Reitweg"
            if tag == "bus_guideway": return "Busspur"
            if tag == "bus_stop": return "Bushaltestelle"
            if tag == "byway": return "Umgehungsstraße"
            if tag == "construction": return "Straße im Bau"
            if tag == "cycleway": return "Radweg"
            if tag == "distance_marker": return "Kilometerstein"
            if tag == "emergency_access_point": return "Notrufpunkt"
            if tag == "footway": return "Gehweg"
            if tag == "footway_sidewalk": return "Bürgersteig"
            if tag == "footway_crossing": return "Fußgängerüberweg"
            if tag == "ford": return "Furt"
            if tag == "gate": return "Tor"
            if tag == "living_street": return "Spielstraße"
            if tag == "minor": return "Nebenstraße"
            if tag == "motorway": return "Autobahn"
            if tag == "motorway_junction": return "Autobahnkreuz"
            if tag == "motorway_link": return "Autobahnauffahrt"
            if tag == "path": return "Pfad"
            if tag == "pedestrian": return "Fußgängerzone"
            if tag == "platform": return "Plattform"
            if tag == "primary": return "Primärstraße"
            if tag == "primary_link": return "Primärauffahrt"
            if tag == "raceway": return "Rennweg"
            if tag == "residential": return "Wohnstraße"
            if tag == "road": return "Straße"
            if tag == "secondary": return "Landstraße"
            if tag == "secondary_link": return "Landstraße"
            if tag == "service": return "Anliegerstraße"
            if tag == "services": return "Autobahnraststätte"
            if tag == "steps": return "Treppe"
            if tag == "stile": return "Zaunübertritt"
            if tag == "tertiary": return "Nebenstraße"
            if tag == "tertiary_link": return "Nebenstraße"
            if tag == "track": return "Feldweg"
            if tag == "trail": return "Pfad"
            if tag == "trunk": return "Fernverkehrsstraße"
            if tag == "trunk_link": return "Fernstraßenauffahrt"
            if tag == "unclassified": return "Landstraße"
            if tag == "unsurfaced": return "nichtasphaltierte Straße"
            if tag == "crossing": return "Querung"
            if tag == "roundabout": return "Kreisverkehr"
            if tag == "traffic_signals": return "Ampelkreuzung"

        if category == "railway":
            if tag == "abandoned": return "aufgelassene Bahnstrecke"
            if tag == "construction": return "Eisenbahn im Bau"
            if tag == "disused": return "unbenutzte Bahnstrecke"
            if tag == "disused_station": return "unbenutzer Bahnhof"
            if tag == "funicular": return "Seilbahn"
            if tag == "halt": return "Haltepunkt"
            if tag == "historic_station": return "historischer Bahnhof"
            if tag == "junction": return "Bahnknotenpunkt"
            if tag == "light_rail": return "S-Bahn"
            if tag == "miniature": return "Miniaturbahn"
            if tag == "monorail": return "Einschienenbahn"
            if tag == "narrow_gauge": return "Schmalspurbahn"
            if tag == "platform": return "Bahnsteig"
            if tag == "preserved": return "bewahrte Bahnstrecke"
            if tag == "rail": return "Eisenbahn"
            if tag == "spur": return "Bahnstrecke"
            if tag == "station": return "Bahnhof"
            if tag == "subway_entrance": return "U-Bahn-Zugang"
            if tag == "subway": return "U-Bahn"
            if tag == "switch": return "Weiche"
            if tag == "tram": return "Straßenbahn"
            if tag == "tram_stop": return "Straßenbahnhaltestelle"
            if tag == "yard": return "Rangierbahnhof"
            if tag in ["crossing", "level_crossing"]: return "Bahnübergang"

        if category == "public_transport":
            if tag == "bus": return "Bushaltestelle"
            if tag == "tram": return "Straßenbahnhaltestelle"
            if tag == "train": return "Bahnhof"
            if tag == "light_rail": return "S-Bahnhof"
            if tag == "subway": return "U-Bahnhof"
            if tag == "ferry": return "Fährstation"
            if tag == "aerialway": return "Liftstation"
            if tag == "unknown": return "Haltestelle"

        if category == "bridge":
            if tag == "yes": return "Brücke"

        if category == "crossing":
            if tag == "traffic_signals": return "Ampel"
            if tag == "zebra": return "Zebrastreifen"
            if tag == "uncontrolled": return "ungeregelt"
            if tag == "unmarked": return "unmarkiert"

        if category == "historic":
            if tag == "archaeological_site": return "Ausgrabungsstätte"
            if tag == "battlefield": return "Kampfgebiet"
            if tag == "boundary_stone": return "Grenzstein"
            if tag == "building": return "historisches Gebäude"
            if tag == "castle": return "Schloss"
            if tag == "church": return "Kirche"
            if tag == "house": return "historisches Haus"
            if tag == "icon": return "Symbol"
            if tag == "manor": return "Gut"
            if tag == "memorial": return "Gedenkstätte"
            if tag == "mine": return "historisches Bergwerk"
            if tag == "monument": return "Monument"
            if tag == "museum": return "Museum"
            if tag == "ruins": return "Ruine"
            if tag == "tower": return "Turm"
            if tag == "wayside_cross": return "Wegkreuz"
            if tag == "wayside_shrine": return "Schrein"
            if tag == "wreck": return "Schiffswrack"
            if tag == "yes": return "Historischer Ort"

        if category == "landuse":
            if tag == "allotments": return "Kleingartenanlage"
            if tag == "basin": return "Becken"
            if tag == "brownfield": return "Brachfläche"
            if tag == "cemetery": return "Friedhof"
            if tag == "commercial": return "Gewerbegebiet"
            if tag == "conservation": return "Naturschutzgebiet"
            if tag == "construction": return "Baustelle"
            if tag == "farm": return "Bauernhof"
            if tag == "farmland": return "Ackerland"
            if tag == "farmyard": return "Hof"
            if tag == "forest": return "Wald"
            if tag == "grass": return "Rasenfläche"
            if tag == "greenfield": return "unbebaute Fläche"
            if tag == "industrial": return "Industriegebiet"
            if tag == "landfill": return "Müllhalde"
            if tag == "meadow": return "Wiese"
            if tag == "military": return "Militärgebiet"
            if tag == "mine": return "Bergwerk"
            if tag == "mountain": return "Berg"
            if tag == "nature_reserve": return "Naturschutzgebiet"
            if tag == "park": return "Park"
            if tag == "piste": return "Piste"
            if tag == "plaza": return "großer Platz"
            if tag == "quarry": return "Steinbruch"
            if tag == "railway": return "Eisenbahn"
            if tag == "recreation_ground": return "Naherholungsgebiet"
            if tag == "reservoir": return "Reservoir"
            if tag == "residential": return "Siedlung"
            if tag == "retail": return "Einzelhandel"
            if tag == "village_green": return "Grünanlage"
            if tag == "vineyard": return "Weingut"
            if tag == "wetland": return "Feuchtgebiet"
            if tag == "wood": return "Wald"

        if category == "leisure":
            if tag == "beach_resort": return "Freibad"
            if tag == "common": return "Gemeindeland"
            if tag == "fishing": return "Fischereigrund"
            if tag == "garden": return "Garten"
            if tag == "golf_course": return "Golfplatz"
            if tag == "hackerspace": return "Hackerspace"
            if tag == "ice_rink": return "Eislaufplatz"
            if tag == "marina": return "Yachthafen"
            if tag == "miniature_golf": return "Minigolf"
            if tag == "nature_reserve": return "Naturschutzgebiet"
            if tag == "park": return "Park"
            if tag == "pitch": return "Sportplatz"
            if tag == "playground": return "Spielplatz"
            if tag == "recreation_ground": return "Naherholungsgebiet"
            if tag == "slipway": return "Slipanlage"
            if tag == "sports_centre": return "Sportzentrum"
            if tag == "stadium": return "Stadion"
            if tag == "swimming_pool": return "Schwimmbecken"
            if tag == "track": return "Rennstrecke"
            if tag == "water_park": return "Wasserpark"

        if category == "man_made":
            if tag == "surveillance": return "Überwachungskamera"

        if category == "natural":
            if tag == "bay": return "Bucht"
            if tag == "beach": return "Strand"
            if tag == "cape": return "Kap"
            if tag == "cave_entrance": return "Höhleneingang"
            if tag == "channel": return "Kanal"
            if tag == "cliff": return "Klippe"
            if tag == "coastline": return "Küstenlinie"
            if tag == "crater": return "Krater"
            if tag == "feature": return "Merkmal"
            if tag == "fell": return "kahler Berg"
            if tag == "fjord": return "Fjord"
            if tag == "geyser": return "Geysir"
            if tag == "glacier": return "Gletscher"
            if tag == "heath": return "Heide"
            if tag == "hill": return "Erhebung"
            if tag == "island": return "Insel"
            if tag == "land": return "Land"
            if tag == "marsh": return "Marschland"
            if tag == "moor": return "Moor"
            if tag == "mud": return "Schlamm"
            if tag == "peak": return "Gipfel"
            if tag == "point": return "Punkt"
            if tag == "reef": return "Riff"
            if tag == "ridge": return "Grat"
            if tag == "river": return "Fluss"
            if tag == "rock": return "Stein"
            if tag == "scree": return "Geröll"
            if tag == "scrub": return "Busch"
            if tag == "shoal": return "Untiefe"
            if tag == "spring": return "Quelle"
            if tag == "strait": return "Straße"
            if tag == "tree": return "Baum"
            if tag == "valley": return "Tal"
            if tag == "volcano": return "Vulkan"
            if tag == "water": return "Wasser"
            if tag == "wetland": return "Feuchtgebiet"
            if tag == "wetlands": return "Feuchtgebiet"
            if tag == "wood": return "Wald"

        if category == "place":
            if tag == "city": return "Stadt"
            if tag == "country": return "Land"
            if tag == "county": return "Bezirk"
            if tag == "farm": return "Gehöft"
            if tag == "hamlet": return "Weiler"
            if tag == "house": return "Haus"
            if tag == "houses": return "Häuser"
            if tag == "island": return "Insel"
            if tag == "islet": return "Inselchen"
            if tag == "locality": return "Ortschaft"
            if tag == "moor": return "Moor"
            if tag == "municipality": return "Gemeinde"
            if tag == "postcode": return "Postleitzahl"
            if tag == "region": return "Region"
            if tag == "sea": return "Meer"
            if tag == "state": return "Bundesland"
            if tag == "subdivision": return "Untergruppe"
            if tag == "suburb": return "Stadtteil"
            if tag == "town": return "Stadt"
            if tag == "unincorporated_area": return "gemeindefreies Gebiet"
            if tag == "village": return "Dorf"

        if category == "office":
            if tag == "government": return "Amt oder Behörde"
            if tag == "yes": return "Büro"

        if category == "shop":
            if tag == "alcohol": return "Spirituosenladen"
            if tag == "apparel": return "Bekleidungsgeschäft"
            if tag == "art": return "Kunstladen"
            if tag == "bakery": return "Bäckerei"
            if tag == "beauty": return "Parfümerie"
            if tag == "beverages": return "Getränkemarkt"
            if tag == "bicycle": return "Fahrradgeschäft"
            if tag == "books": return "Buchgeschäft"
            if tag == "butcher": return "Fleischerei"
            if tag == "car": return "Autohaus"
            if tag == "car_dealer": return "Autohaus"
            if tag == "car_parts": return "Autoteilehändler"
            if tag == "car_repair": return "Autowerkstatt"
            if tag == "carpet": return "Teppichgeschäft"
            if tag == "charity": return "Wohltätigkeitsladen"
            if tag == "chemist": return "Drogerie"
            if tag == "clothes": return "Bekleidungsgeschäft"
            if tag == "computer": return "Computergeschäft"
            if tag == "confectionery": return "Süßwarengeschäft"
            if tag == "convenience": return "Tante-Emma-Laden"
            if tag == "copyshop": return "Copyshop"
            if tag == "cosmetics": return "Kosmetikgeschäft"
            if tag == "department_store": return "Warenhäuser"
            if tag == "discount": return "Diskontladen"
            if tag == "doityourself": return "Baumarkt"
            if tag == "drugstore": return "Drogerie"
            if tag == "dry_cleaning": return "Textilreinigung"
            if tag == "electronics": return "Elektronikgeschäft"
            if tag == "estate_agent": return "Imobilienhändler"
            if tag == "farm": return "Hofladen"
            if tag == "fashion": return "Modegeschäft"
            if tag == "fish": return "Angelladen"
            if tag == "florist": return "Blumenladen"
            if tag == "food": return "Lebensmittelladen"
            if tag == "funeral_directors": return "Bestattungsunternehmen"
            if tag == "furniture": return "Möbelgeschäft"
            if tag == "gallery": return "Galerie"
            if tag == "garden_centre": return "Gärtnerei"
            if tag == "general": return "Gemischtwarenladen"
            if tag == "gift": return "Geschenkeladen"
            if tag == "greengrocer": return "Obst- und Gemüsehandlung"
            if tag == "grocery": return "Lebensmittelladen"
            if tag == "hairdresser": return "Frisör"
            if tag == "hardware": return "Eisenwarenhandlung"
            if tag == "hifi": return "Unterhaltungselektronikladen"
            if tag == "insurance": return "Versicherungsbüro"
            if tag == "jewelry": return "Juwelier"
            if tag == "kiosk": return "Kiosk"
            if tag == "laundry": return "Waschsalon"
            if tag == "mall": return "Einkaufszentrum"
            if tag == "market": return "Markt"
            if tag == "mobile_phone": return "Handygeschäft"
            if tag == "motorcycle": return "Motorradgeschäft"
            if tag == "music": return "Musikladen"
            if tag == "newsagent": return "Zeitschriftenladen"
            if tag == "optician": return "Optiker"
            if tag == "organic": return "Bioladen"
            if tag == "outdoor": return "Outdoorladen"
            if tag == "pet": return "Tierhandlung"
            if tag == "photo": return "Fotoladen"
            if tag == "salon": return "Salon"
            if tag == "shoes": return "Schuhgeschäft"
            if tag == "shopping_centre": return "Einkaufszentrum"
            if tag == "sports": return "Sportgeschäft"
            if tag == "stationery": return "Schreibwarenladen"
            if tag == "supermarket": return "Supermarkt"
            if tag == "toys": return "Spielwarengeschäft"
            if tag == "travel_agency": return "Reisebüro"
            if tag == "video": return "Videothek"
            if tag == "wine": return "Weingeschäft"

        if category == "tourism":
            if tag == "alpine_hut": return "Berghütte"
            if tag == "artwork": return "Kunstwerk"
            if tag == "attraction": return "Attraktion"
            if tag == "bed_and_breakfast": return "Unterkunft"
            if tag == "cabin": return "Hütte"
            if tag == "camp_site": return "Campingplatz"
            if tag == "caravan_site": return "Wohnwagen-Stellplatz"
            if tag == "chalet": return "Almhütte"
            if tag == "guest_house": return "Pension"
            if tag == "hostel": return "Jugendherberge"
            if tag == "hotel": return "Hotel"
            if tag == "information": return "Touristen-Information"
            if tag == "lean_to": return "Anbau"
            if tag == "motel": return "Motel"
            if tag == "museum": return "Museum"
            if tag == "picnic_site": return "Piknikplatz"
            if tag == "theme_park": return "Vergnügungspark"
            if tag == "valley": return "Tal"
            if tag == "viewpoint": return "Aussichtspunkt"
            if tag == "zoo": return "Zoo"

        if category == "waterway":
            if tag == "boatyard": return "Werft"
            if tag == "canal": return "Kanal"
            if tag == "connector": return "Wasserstraßenverbindung"
            if tag == "dam": return "Staudamm"
            if tag == "derelict_canal": return "Aufgelassener Kanal"
            if tag == "ditch": return "Wassergraben"
            if tag == "dock": return "Dock"
            if tag == "drain": return "Entwässerungsgraben"
            if tag == "lock": return "Schleuse"
            if tag == "lock_gate": return "Schleusentor"
            if tag == "mineral_spring": return "Mineralquelle"
            if tag == "mooring": return "Anlegeplatz"
            if tag == "rapids": return "Stromschnellen"
            if tag == "river": return "Fluss"
            if tag == "riverbank": return "Flussufer"
            if tag == "stream": return "Bach"
            if tag == "wadi": return "Trockental"
            if tag == "water_point": return "Wasserpunkt"
            if tag == "waterfall": return "Wasserfall"
            if tag == "weir": return "Wehr"
        return tag


    def translate_to_english(self, category, tag):
        if category == "message":
            if tag == "map_not_available_or_incompatible": return "Map is not available or incompatible"
            if tag == "database_error": return "Error during database access"
            if tag == "no_route_options": return "No route options transmitted"
            if tag == "no_route_factor_option": return "The factor for the route indirection calculation is missing"
            if tag == "no_session_id_option": return "Missing session id"
            if tag == "old_request_still_running": return "The server still calculates your prior request. Please wait at least 3 minutes."
            if tag == "server_busy": return "Currently the server is busy. Please try again later."
            if tag == "no_source_route": return "No route transmitted"
            if tag == "source_route_incomplete": return "The transmitted route query is incomplete"
            if tag == "no_start_point": return "No start point transmitted"
            if tag == "start_point_no_name": return "The name of the start point is missing"
            if tag == "start_point_no_latitude": return "The latitude value of the start point is missing"
            if tag == "start_point_no_longitude": return "The longitude value of the start point is missing"
            if tag == "start_point_no_type": return "The type value of the start point is missing"
            if tag == "no_way_id": return "No Way-Id transmitted"
            if tag == "no_node_id": return "No node id transmitted"
            if tag == "no_next_node_id": return "No next node id transmitted"
            if tag == "node_id_invalid": return "The transmitted Waypoint-Id is invalid"
            if tag == "way_id_invalid": return "The transmitted Way-Id is invalid"
            if tag == "source_route_no_transport_parts": return "The transmitted route lacks a public transport segment"
            if tag == "source_route_multiple_transport_parts": return "The transmitted route consists of multiple public transport segments"
            if tag == "no_address_string": return "No address string transmitted"
            if tag == "address_invalid": return "Found no coordinates for the given address"
            if tag == "no_latitude_value": return "The latitude value is missing"
            if tag == "no_longitude_value": return "The longitude value is missing"
            if tag == "no_range_value": return "The radius value is missing"
            if tag == "no_tags_value": return "The poi tags are missing"
            if tag == "no_public_transport_provider": return "The public transport provider is missing"
            if tag == "no_address_for_this_coordinates": return "Found no address for the given coordinates"
            if tag == "no_station_for_this_coordinates": return "Found no station for this coordinates"
            if tag == "bahn_server_down": return "The server of the Deutsche Bahn is not accessible"
            if tag == "no_bug_report_file_name": return "The bug report file name is missing"
            if tag == "no_bug_report_contents": return "The bug report contents is missing"
            if tag == "process_canceled": return "Process canceled"

        if category == "footway_creator":
            if tag == "first_segment": return "Nameless route segment"
            if tag == "last_segment": return "Nameless route segment"
            if tag == "via_point_label": return "Via point %d, %s"
            if tag == "route_description_without_transport": return textwrap.dedent("""\
                The total length of the route is %d meters and it consists of %d intersections""")
            if tag == "route_description_with_single_transport": return textwrap.dedent("""\
                    The total length of the route is %d meters and it consists of %d intersections and one public transport part.
                    Departure in %d Minutes from the station %s with line %s to %s.""")
            if tag == "route_description_with_multi_transport": return textwrap.dedent("""\
                    The total length of the route is %d meters and it consists of %d intersections and %d public transport parts.
                    Departure in %d Minutes from the station %s with line %s to %s.""")

        if category == "transport_creator":
            if tag == "footway_place_holder": return "Placeholder for a walking route segment"
            if tag == "same_station": return "Continuation from same station"
            if tag == "opposite_station": return "Continuation from opposite station"
            if tag == "nearby_station": return "Continuation from nearby station"
            if tag == "nearby_station_no_exact_pos": return "Continuation from nearby station, exact position unknown"
            if tag == "within_station": return "Continuation within this station"
            if tag == "different_station": return "Continuation from different station"
            if tag == "transport_route_description": return textwrap.dedent("""\
                    Departure in %d minutes, Duration: %d minutes, %d changes,
                    Transportation vehicles: %s, Route length: %d meters""")
            if tag == "transport_route_description_no_time": return textwrap.dedent("""\
                    Departure in %d minutes, Duration: %d minutes, %d changes (time limited),
                    Transportation vehicles: %s, Route length: %d meters""")

        if category == "poi":
            if tag == "address": return "Address"
            if tag == "hiking_trail": return "Hiking trail"
            if tag == "way_point": return "Way point"
            if tag == "way_segment": return "Way segment"

        if category == "smoothness":
            if tag == "excellent": return "Excellent"
            if tag == "good": return "Good"
            if tag == "intermediate": return "Intermediate"
            if tag == "bad": return "Bad"
            if tag == "very_bad": return "Bad"
            if tag == "horrible": return "Very bad"
            if tag == "very_horrible": return "Very bad"
            if tag == "impassable": return "Impassable for wheeled vehicles"

        if category == "surface":
            if tag == "unpaved": return "unpaved"
            if tag == "paved": return "paved"
            if tag == "asphalt": return "asphalt"
            if tag == "cobblestone:flattened": return "cobblestone"
            if tag == "cobblestone": return "cobblestone"
            if tag == "concrete:lanes": return "concrete plates"
            if tag == "concrete": return "concrete"
            if tag == "paving_stones:20": return "paving stones"
            if tag == "paving_stones:30": return "paving stones"
            if tag == "paving_stones": return "paving stones"
            if tag == "sett": return "paving stones"
            if tag == "compacted": return "compacted gravel"
            if tag == "fine_gravel": return "compacted gravel"
            if tag == "earth": return "trail"
            if tag == "ground": return "trail"
            if tag == "grass_paver": return "grass paver"
            if tag == "grass": return "grass"
            if tag == "metal": return "metal"
            if tag == "gravel": return "pebble stone"
            if tag == "pebblestone": return "pebble stone"
            if tag == "sand": return "sand"
            if tag == "mud": return "mud"
            if tag == "ice": return "ice"
            if tag == "snow": return "snow"
            if tag == "wood": return "wood"
            if tag == "tartan": return "tartan surface"
            if tag == "artificial_turf": return "artificial turf"
            if tag == "decoturf": return "artificial turf"
            if tag == "clay": return "tennis or soccer pitch surface"

        if category == "aeroway":
            if tag == "aerodrome": return "Airport"
            if tag == "terminal": return "Airport terminal"

        if category == "amenity":
            if tag == "animal_boarding": return "Animal boarding facility"
            if tag == "animal_shelter": return "Animal shelter"
            if tag == "arts_centre": return "Arts Centre"
            if tag == "atm": return "ATM"
            if tag == "auditorium": return "Auditorium"
            if tag == "bank": return "Bank"
            if tag == "bar": return "Bar"
            if tag == "bbq": return "Barbecue"
            if tag == "bench": return "Bench"
            if tag == "bicycle_parking": return "Cycle Parking"
            if tag == "bicycle_rental": return "Cycle Rental"
            if tag == "brothel": return "Brothel"
            if tag == "bureau_de_change": return "Bureau de Change"
            if tag == "bus_station": return "Bus Station"
            if tag == "cafe": return "Cafe"
            if tag == "car_rental": return "Car Rental"
            if tag == "car_sharing": return "Car Share"
            if tag == "car_wash": return "Car Wash"
            if tag == "casino": return "Casino"
            if tag == "cinema": return "Cinema"
            if tag == "clinic": return "Clinic"
            if tag == "club": return "Club"
            if tag == "college": return "College"
            if tag == "community_centre": return "Community Centre"
            if tag == "courthouse": return "Courthouse"
            if tag == "crematorium": return "Crematorium"
            if tag == "dentist": return "Dentist"
            if tag == "doctors": return "Doctor"
            if tag == "dormitory": return "Dormitory"
            if tag == "drinking_water": return "Drinking Water"
            if tag == "driving_school": return "Driving School"
            if tag == "embassy": return "Embassy"
            if tag == "emergency_phone": return "Emergency Phone"
            if tag == "fast_food": return "Fast Food"
            if tag == "ferry_terminal": return "Ferry Terminal"
            if tag == "fire_hydrant": return "Fire Hydrant"
            if tag == "fire_station": return "Fire Station"
            if tag == "fountain": return "Fountain"
            if tag == "fuel": return "Fuel"
            if tag == "grave_yard": return "Grave Yard"
            if tag == "gym": return "Fitness Centre"
            if tag == "hall": return "Hall"
            if tag == "health_centre": return "Health Centre"
            if tag == "hospital": return "Hospital"
            if tag == "hotel": return "Hotel"
            if tag == "hunting_stand": return "Hunting Stand"
            if tag == "ice_cream": return "Ice Cream"
            if tag == "kindergarten": return "Kindergarten"
            if tag == "kneipp_water_cure": return "kneipp water cure"
            if tag == "library": return "Library"
            if tag == "market": return "Market"
            if tag == "marketplace": return "Marketplace"
            if tag == "mountain_rescue": return "Mountain Rescue"
            if tag == "nightclub": return "Night Club"
            if tag == "nursery": return "Nursery"
            if tag == "nursing_home": return "Nursing Home"
            if tag == "office": return "Office"
            if tag == "park": return "Park"
            if tag == "parking": return "Parking"
            if tag == "pharmacy": return "Pharmacy"
            if tag == "place_of_worship": return "Church"
            if tag == "police": return "Police"
            if tag == "post_box": return "Post Box"
            if tag == "post_office": return "Post Office"
            if tag == "preschool": return "Pre-School"
            if tag == "prison": return "Prison"
            if tag == "pub": return "Pub"
            if tag == "public_building": return "Public Building"
            if tag == "public_market": return "Public Market"
            if tag == "reception_area": return "Reception Area"
            if tag == "recycling": return "Recycling Point"
            if tag == "restaurant": return "Restaurant"
            if tag == "retirement_home": return "Retirement Home"
            if tag == "sauna": return "Sauna"
            if tag == "school": return "School"
            if tag == "shelter": return "Shelter"
            if tag == "shop": return "Shop"
            if tag == "shopping": return "Shopping"
            if tag == "social_club": return "Social Club"
            if tag == "studio": return "Studio"
            if tag == "supermarket": return "Supermarket"
            if tag == "swingerclub": return "Swinger Club"
            if tag == "taxi": return "Taxi"
            if tag == "telephone": return "Telephone"
            if tag == "theatre": return "Theatre"
            if tag == "toilets": return "Toilet"
            if tag == "townhall": return "Town Hall"
            if tag == "university": return "University"
            if tag == "vending_machine": return "Vending Machine"
            if tag == "veterinary": return "Veterinary Surgery"
            if tag == "village_hall": return "Village Hall"
            if tag == "waste_basket": return "Waste Basket"
            if tag == "wifi": return "WiFi Access"
            if tag == "youth_centre": return "Youth Centre"

        if category == "building":
            if tag == "apartments": return "Apartment Block"
            if tag == "block": return "Building Block"
            if tag == "bunker": return "Bunker"
            if tag == "chapel": return "Chapel"
            if tag == "church": return "Church"
            if tag == "city_hall": return "City Hall"
            if tag == "commercial": return "Commercial Building"
            if tag == "dormitory": return "Dormitory"
            if tag == "entrance": return "Building Entrance"
            if tag == "faculty": return "Faculty Building"
            if tag == "farm": return "Farm Building"
            if tag == "flats": return "Flats"
            if tag == "garage": return "Garage"
            if tag == "hall": return "Hall"
            if tag == "hospital": return "Hospital Building"
            if tag == "hotel": return "Hotel"
            if tag == "house": return "House"
            if tag == "industrial": return "Industrial Building"
            if tag == "office": return "Office Building"
            if tag == "public": return "Public Building"
            if tag == "residential": return "Residential Building"
            if tag == "retail": return "Retail Building"
            if tag == "school": return "School Building"
            if tag == "shop": return "Shop"
            if tag == "stadium": return "Stadium"
            if tag == "store": return "Store"
            if tag == "terrace": return "Terrace"
            if tag == "tower": return "Tower"
            if tag == "train_station": return "Railway Station"
            if tag == "university": return "University Building"
            if tag == "building": return "Building"

        if category == "entrance":
            if tag == "yes": return "Entrance"
            if tag == "main": return "Main Entrance"
            if tag == "service": return "Service Entrance"
            if tag == "emergency": return "Emergency Exit"
            if tag == "exit": return "Only Exit"
            if tag == "subway_entrance": return "Subway Entrance"
            if tag == "entrance": return "Entrance"

        if category == "highway":
            if tag == "bridleway": return "Bridleway"
            if tag == "bus_guideway": return "Guided Bus Lane"
            if tag == "bus_stop": return "Bus Stop"
            if tag == "byway": return "Byway"
            if tag == "construction": return "Highway under Construction"
            if tag == "cycleway": return "Cycle Path"
            if tag == "distance_marker": return "Distance Marker"
            if tag == "emergency_access_point": return "Emergency Access Point"
            if tag == "footway": return "Footpath"
            if tag == "footway_sidewalk": return "Sidewalk"
            if tag == "footway_crossing": return "Pedestrian crossing"
            if tag == "ford": return "Ford"
            if tag == "gate": return "Gate"
            if tag == "living_street": return "Living Street"
            if tag == "minor": return "Minor Road"
            if tag == "motorway": return "Motorway"
            if tag == "motorway_junction": return "Motorway Junction"
            if tag == "motorway_link": return "Motorway Road"
            if tag == "path": return "Path"
            if tag == "pedestrian": return "Pedestrian Way"
            if tag == "platform": return "Platform"
            if tag == "primary": return "Primary Road"
            if tag == "primary_link": return "Primary Road"
            if tag == "raceway": return "Raceway"
            if tag == "residential": return "Residential"
            if tag == "rest_area": return "Rest Area"
            if tag == "road": return "Road"
            if tag == "secondary": return "Secondary Road"
            if tag == "secondary_link": return "Secondary Road"
            if tag == "service": return "Service Road"
            if tag == "services": return "Service Area"
            if tag == "steps": return "Steps"
            if tag == "stile": return "Stile"
            if tag == "tertiary": return "Tertiary Road"
            if tag == "tertiary_link": return "Tertiary Road"
            if tag == "track": return "Track"
            if tag == "trail": return "Trail"
            if tag == "trunk": return "Trunk Road"
            if tag == "trunk_link": return "Trunk Road"
            if tag == "unclassified": return "Unclassified Road"
            if tag == "unsurfaced": return "Unsurfaced Road"
            if tag == "crossing": return "crossing"
            if tag == "roundabout": return "Roundabout"
            if tag == "traffic_signals": return "Traffic light intersection"

        if category == "railway":
            if tag == "abandoned": return "Abandoned Railway"
            if tag == "construction": return "Railway under Construction"
            if tag == "disused": return "Disused Railway"
            if tag == "disused_station": return "Disused Railway Station"
            if tag == "funicular": return "Funicular Railway"
            if tag == "halt": return "Train Stop"
            if tag == "historic_station": return "Historic Railway Station"
            if tag == "junction": return "Railway Junction"
            if tag == "light_rail": return "Light Rail"
            if tag == "miniature": return "Miniature Railway"
            if tag == "monorail": return "Monorail"
            if tag == "narrow_gauge": return "Narrow Gauge Railway"
            if tag == "platform": return "Railway Platform"
            if tag == "preserved": return "Preserved Railway"
            if tag == "rail": return "Railway"
            if tag == "spur": return "Railway Spur"
            if tag == "station": return "Railway Station"
            if tag == "subway_entrance": return "Subway Entrance"
            if tag == "subway": return "Subway Station"
            if tag == "switch": return "Railway Points"
            if tag == "tram": return "Tramway"
            if tag == "tram_stop": return "Tram Stop"
            if tag == "yard": return "Railway Yard"
            if tag in ["crossing", "level_crossing"]: return "Railway crossing"

        if category == "public_transport":
            if tag == "bus": return "Bus Stop"
            if tag == "tram": return "Tram stop"
            if tag == "train": return "Train Station"
            if tag == "light_rail": return "Lightrail Station"
            if tag == "subway": return "Subway Station"
            if tag == "ferry": return "Ferry Station"
            if tag == "aerialway": return "Aerial cableway station"
            if tag == "unknown": return "Station"

        if category == "bridge":
            if tag == "yes": return "Bridge"

        if category == "crossing":
            if tag == "traffic_signals": return "traffic signals"
            if tag == "zebra": return "zebra"
            if tag == "uncontrolled": return "uncontrolled"
            if tag == "unmarked": return "unmarked"

        if category == "historic":
            if tag == "archaeological_site": return "Archaeological Site"
            if tag == "battlefield": return "Battlefield"
            if tag == "boundary_stone": return "Boundary Stone"
            if tag == "building": return "Building"
            if tag == "castle": return "Castle"
            if tag == "church": return "Church"
            if tag == "house": return "House"
            if tag == "icon": return "Icon"
            if tag == "manor": return "Manor"
            if tag == "memorial": return "Memorial"
            if tag == "mine": return "Mine"
            if tag == "monument": return "Monument"
            if tag == "museum": return "Museum"
            if tag == "ruins": return "Ruin"
            if tag == "tower": return "Tower"
            if tag == "wayside_cross": return "Wayside Cross"
            if tag == "wayside_shrine": return "Wayside Shrine"
            if tag == "wreck": return "Wreck"
            if tag == "yes": return "Historic place"

        if category == "landuse":
            if tag == "allotments": return "Allotment"
            if tag == "basin": return "Basin"
            if tag == "brownfield": return "Brownfield Land"
            if tag == "cemetery": return "Cemetery"
            if tag == "commercial": return "Commercial Area"
            if tag == "conservation": return "Conservation"
            if tag == "construction": return "Construction"
            if tag == "farm": return "Farm"
            if tag == "farmland": return "Farmland"
            if tag == "farmyard": return "Farmyard"
            if tag == "forest": return "Forest"
            if tag == "grass": return "Grass"
            if tag == "greenfield": return "Greenfield Land"
            if tag == "industrial": return "Industrial Area"
            if tag == "landfill": return "Landfill"
            if tag == "meadow": return "Meadow"
            if tag == "military": return "Military Area"
            if tag == "mine": return "Mine"
            if tag == "mountain": return "Mountain"
            if tag == "nature_reserve": return "Nature Reserve"
            if tag == "park": return "Park"
            if tag == "piste": return "Piste"
            if tag == "plaza": return "Plaza"
            if tag == "quarry": return "Quarry"
            if tag == "railway": return "Railway"
            if tag == "recreation_ground": return "Recreation Ground"
            if tag == "reservoir": return "Reservoir"
            if tag == "residential": return "Residential Area"
            if tag == "retail": return "Retail"
            if tag == "village_green": return "Village Green"
            if tag == "vineyard": return "Vineyard"
            if tag == "wetland": return "Wetland"
            if tag == "wood": return "Wood"

        if category == "leisure":
            if tag == "beach_resort": return "Beach Resort"
            if tag == "common": return "Common Land"
            if tag == "fishing": return "Fishing Area"
            if tag == "garden": return "Garden"
            if tag == "golf_course": return "Golf Course"
            if tag == "hackerspace": return "Hackerspace"
            if tag == "ice_rink": return "Ice Rink"
            if tag == "marina": return "Marina"
            if tag == "miniature_golf": return "Miniature Golf"
            if tag == "nature_reserve": return "Nature Reserve"
            if tag == "park": return "Park"
            if tag == "pitch": return "Sports Pitch"
            if tag == "playground": return "Playground"
            if tag == "recreation_ground": return "Recreation Ground"
            if tag == "slipway": return "Slipway"
            if tag == "sports_centre": return "Sports Centre"
            if tag == "stadium": return "Stadium"
            if tag == "swimming_pool": return "Swimming Pool"
            if tag == "track": return "Running Track"
            if tag == "water_park": return "Water Park"
            if tag == "slipway": return "Boat Ramp"

        if category == "man_made":
            if tag == "surveillance": return "Surveillance camera"

        if category == "natural":
            if tag == "bay": return "Bay"
            if tag == "beach": return "Beach"
            if tag == "cape": return "Cape"
            if tag == "cave_entrance": return "Cave Entrance"
            if tag == "channel": return "Channel"
            if tag == "cliff": return "Cliff"
            if tag == "coastline": return "Coastline"
            if tag == "crater": return "Crater"
            if tag == "feature": return "Feature"
            if tag == "fell": return "Fell"
            if tag == "fjord": return "Fjord"
            if tag == "geyser": return "Geyser"
            if tag == "glacier": return "Glacier"
            if tag == "heath": return "Heath"
            if tag == "hill": return "Hill"
            if tag == "island": return "Island"
            if tag == "land": return "Land"
            if tag == "marsh": return "Marsh"
            if tag == "moor": return "Moor"
            if tag == "mud": return "Mud"
            if tag == "peak": return "Peak"
            if tag == "point": return "Point"
            if tag == "reef": return "Reef"
            if tag == "ridge": return "Ridge"
            if tag == "river": return "River"
            if tag == "rock": return "Rock"
            if tag == "scree": return "Scree"
            if tag == "scrub": return "Scrub"
            if tag == "shoal": return "Shoal"
            if tag == "spring": return "Spring"
            if tag == "strait": return "Strait"
            if tag == "tree": return "Tree"
            if tag == "valley": return "Valley"
            if tag == "volcano": return "Volcano"
            if tag == "water": return "Water"
            if tag == "wetland": return "Wetland"
            if tag == "wetlands": return "Wetlands"
            if tag == "wood": return "Wood"

        if category == "place":
            if tag == "city": return "City"
            if tag == "country": return "Country"
            if tag == "county": return "County"
            if tag == "farm": return "Farm"
            if tag == "hamlet": return "Hamlet"
            if tag == "house": return "House"
            if tag == "houses": return "Houses"
            if tag == "island": return "Island"
            if tag == "islet": return "Islet"
            if tag == "locality": return "Locality"
            if tag == "moor": return "Moor"
            if tag == "municipality": return "Municipality"
            if tag == "postcode": return "Postcode"
            if tag == "region": return "Region"
            if tag == "sea": return "Sea"
            if tag == "state": return "State"
            if tag == "subdivision": return "Subdivision"
            if tag == "suburb": return "Suburb"
            if tag == "town": return "Town"
            if tag == "unincorporated_area": return "Unincorporated Area"
            if tag == "village": return "Village"

        if category == "office":
            if tag == "government": return "Government"
            if tag == "yes": return "Office"

        if category == "shop":
            if tag == "alcohol": return "Off License"
            if tag == "apparel": return "Apparel Shop"
            if tag == "art": return "Art Shop"
            if tag == "bakery": return "Bakery"
            if tag == "beauty": return "Beauty Shop"
            if tag == "beverages": return "Beverages Shop"
            if tag == "bicycle": return "Bicycle Shop"
            if tag == "books": return "Book Shop"
            if tag == "butcher": return "Butcher"
            if tag == "car": return "Car Shop"
            if tag == "car_dealer": return "Car Dealer"
            if tag == "car_parts": return "Car Parts"
            if tag == "carpet": return "Carpet Shop"
            if tag == "car_repair": return "Car Repair"
            if tag == "charity": return "Charity Shop"
            if tag == "chemist": return "Chemist"
            if tag == "clothes": return "Clothes Shop"
            if tag == "computer": return "Computer Shop"
            if tag == "confectionery": return "Confectionery Shop"
            if tag == "convenience": return "Convenience Store"
            if tag == "copyshop": return "Copy Shop"
            if tag == "cosmetics": return "Cosmetics Shop"
            if tag == "department_store": return "Department Store"
            if tag == "discount": return "Discount Items Shop"
            if tag == "doityourself": return "Do-It-Yourself"
            if tag == "drugstore": return "Drugstore"
            if tag == "dry_cleaning": return "Dry Cleaning"
            if tag == "electronics": return "Electronics Shop"
            if tag == "estate_agent": return "Estate Agent"
            if tag == "farm": return "Farm Shop"
            if tag == "fashion": return "Fashion Shop"
            if tag == "fish": return "Fish Shop"
            if tag == "florist": return "Florist"
            if tag == "food": return "Food Shop"
            if tag == "funeral_directors": return "Funeral Director"
            if tag == "furniture": return "Furniture"
            if tag == "gallery": return "Gallery"
            if tag == "garden_centre": return "Garden Centre"
            if tag == "general": return "General Store"
            if tag == "gift": return "Gift Shop"
            if tag == "greengrocer": return "Greengrocer"
            if tag == "grocery": return "Grocery Shop"
            if tag == "hairdresser": return "Hairdresser"
            if tag == "hardware": return "Hardware Store"
            if tag == "hifi": return "Hi-Fi"
            if tag == "insurance": return "Insurance"
            if tag == "jewelry": return "Jewelry Shop"
            if tag == "kiosk": return "Kiosk Shop"
            if tag == "laundry": return "Laundry"
            if tag == "mall": return "Mall"
            if tag == "market": return "Market"
            if tag == "mobile_phone": return "Mobile Phone Shop"
            if tag == "motorcycle": return "Motorcycle Shop"
            if tag == "music": return "Music Shop"
            if tag == "newsagent": return "Newsagent"
            if tag == "optician": return "Optician"
            if tag == "organic": return "Organic Food Shop"
            if tag == "outdoor": return "Outdoor Shop"
            if tag == "pet": return "Pet Shop"
            if tag == "photo": return "Photo Shop"
            if tag == "salon": return "Salon"
            if tag == "shoes": return "Shoe Shop"
            if tag == "shopping_centre": return "Shopping Centre"
            if tag == "sports": return "Sports Shop"
            if tag == "stationery": return "Stationery Shop"
            if tag == "supermarket": return "Supermarket"
            if tag == "toys": return "Toy Shop"
            if tag == "travel_agency": return "Travel Agency"
            if tag == "video": return "Video Shop"
            if tag == "wine": return "Off License"

        if category == "tourism":
            if tag == "alpine_hut": return "Alpine Hut"
            if tag == "artwork": return "Artwork"
            if tag == "attraction": return "Attraction"
            if tag == "bed_and_breakfast": return "Bed and Breakfast"
            if tag == "cabin": return "Cabin"
            if tag == "camp_site": return "Camp Site"
            if tag == "caravan_site": return "Caravan Site"
            if tag == "chalet": return "Chalet"
            if tag == "guest_house": return "Guest House"
            if tag == "hostel": return "Hostel"
            if tag == "hotel": return "Hotel"
            if tag == "information": return "Information"
            if tag == "lean_to": return "Lean To"
            if tag == "motel": return "Motel"
            if tag == "museum": return "Museum"
            if tag == "picnic_site": return "Picnic Site"
            if tag == "theme_park": return "Theme Park"
            if tag == "valley": return "Valley"
            if tag == "viewpoint": return "Viewpoint"
            if tag == "zoo": return "Zoo"

        if category == "waterway":
            if tag == "boatyard": return "Boatyard"
            if tag == "canal": return "Canal"
            if tag == "connector": return "Waterway Connector"
            if tag == "dam": return "Dam"
            if tag == "derelict_canal": return "Derelict Canal"
            if tag == "ditch": return "Ditch"
            if tag == "dock": return "Dock"
            if tag == "drain": return "Drain"
            if tag == "lock": return "Lock"
            if tag == "lock_gate": return "Lock Gate"
            if tag == "mineral_spring": return "Mineral Spring"
            if tag == "mooring": return "Mooring"
            if tag == "rapids": return "Rapids"
            if tag == "river": return "River"
            if tag == "riverbank": return "Riverbank"
            if tag == "stream": return "Stream"
            if tag == "wadi": return "Wadi"
            if tag == "waterfall": return "Waterfall"
            if tag == "water_point": return "Water Point"
            if tag == "weir": return "Weir"
        return tag

